---
apiVersion: v1
kind: Service
metadata:
  name: cursosfgv
  namespace: dotnetcore
spec:
  selector:
    app: cursosfgv
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
